### ISSUE TITLE
Can't load population metadata from SLiM tree sequence.

### ISSUE THREAD

**Issue by grahamgower** [MesserLab/SLiM#253]
I can't help but think I'm doing something wrong here... I lightly modified the opening SLiMgui example, and ran it under SLiMgui 06aaa731.
```R
// set up a simple neutral simulation
initialize() {
	initializeMutationRate(1e-7);
	
	// m1 mutation type: neutral
	initializeMutationType("m1", 0.5, "f", 0.0);
	
	// g1 genomic element type: uses m1 for all mutations
	initializeGenomicElementType("g1", m1, 1.0);
	
	// uniform chromosome of length 100 kb with uniform recombination
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
	initializeTreeSeq();
}

// create a population of 500 individuals
1 {
	sim.addSubpop("p1", 500);
	p1.name = "awesomepop";
}

// output samples of 10 genomes periodically, all fixed mutations at end
1000 late() { p1.outputSample(10); }
2000 late() { p1.outputSample(10); }
2000 late() { sim.treeSeqOutput("/tmp/names.ts"); }
```

And then went to play with the population metadata.

```
t490:tmp $ tskit populations names.ts
id      metadata
Traceback (most recent call last):
  File "/home/grg/.local/bin/tskit", line 8, in <module>
    sys.exit(tskit_main())
  File "/home/grg/.local/lib/python3.9/site-packages/tskit/cli.py", line 284, in tskit_main
    args.runner(args)
  File "/home/grg/.local/lib/python3.9/site-packages/tskit/cli.py", line 122, in run_populations
    tree_sequence.dump_text(populations=sys.stdout)
  File "/home/grg/.local/lib/python3.9/site-packages/tskit/trees.py", line 3722, in dump_text
    metadata = population.metadata
  File "/home/grg/.local/lib/python3.9/site-packages/tskit/metadata.py", line 714, in __get__
    row, "_metadata", row._metadata_decoder(row._metadata)
  File "/home/grg/.local/lib/python3.9/site-packages/tskit/metadata.py", line 150, in decode
    result = json.loads(encoded.decode())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
That's with tskit 0.3.7, but I get the same thing with tskit 0.4.0b1.

```
t490:tmp $ python
Python 3.9.7 (default, Oct 10 2021, 15:13:22)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tskit, json
>>> tskit.__version__
'0.3.7'
>>> ts = tskit.load("names.ts")
>>> ts.tables.populations.metadata
array([123,  34, 109, 105, 103, 114,  97, 116, 105, 111, 110,  95, 114,
       101,  99, 111, 114, 100, 115,  34,  58,  91,  93,  44,  34, 110,
        97, 109, 101,  34,  58,  34,  97, 119, 101, 115, 111, 109, 101,
       112, 111, 112,  34,  44,  34, 115, 101, 120,  95, 114,  97, 116,
       105, 111,  34,  58,  48,  46,  48,  44,  34, 115, 108, 105, 109,
        95, 105, 100,  34,  58,  49, 125], dtype=int8)
```

Err... What is that?

**Comment by grahamgower** [comment]
Ok, I was definitely doing something wrong. The metadata is encoded and needs to be decoded first. Something like:
```python
>>> import tskit, json
>>> ts = tskit.load("/tmp/names.ts")
>>> bytes(ts.tables.populations.metadata)
b'{"migration_records":[],"name":"awesomepop","sex_ratio":0.0,"slim_id":1}'
>>> bytes(ts.tables.populations.metadata).decode()
'{"migration_records":[],"name":"awesomepop","sex_ratio":0.0,"slim_id":1}'
>>> json.loads(bytes(ts.tables.populations.metadata).decode())
{'migration_records': [], 'name': 'awesomepop', 'sex_ratio': 0.0, 'slim_id': 1}
```

The `tskit populations ...` output looks like a tskit bug. It doesn't work with an msprime tree sequence either.

Sorry for the noise.

**Comment by bhaller** [comment]
OK.  I don't know anything about that end of things; I'm surprised that "decoding" is needed, since the metadata is just a JSON string, but I don't know.
