### ISSUE TITLE
Tree sequences created by SLiM cannot be loaded with tskit

### ISSUE THREAD

**Issue by vsbuffalo** [MesserLab/SLiM#400]
Here is an MRE. Below is the eidos script:

```
// set up a simple neutral simulation
initialize() {
    initializeTreeSeq();
	initializeMutationRate(1e-7);

	// m1 mutation type: neutral
	initializeMutationType("m1", 0.5, "f", 0.0);

	// g1 genomic element type: uses m1 for all mutations
	initializeGenomicElementType("g1", m1, 1.0);

	// uniform chromosome of length 100 kb with uniform recombination
	initializeGenomicElement(g1, 0, 99999);
	initializeRecombinationRate(1e-8);
}

// create a population of 500 individuals
1 early() {
	sim.addSubpop("p1", 500);
}

// output samples of 10 genomes periodically, all fixed mutations at end
2000 late() {
  sim.outputFixedMutations();
  sim.treeSeqOutput("mre.tree");
}
```

below is how I tried to load it into python:

```python
python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tskit
>>> tskit.load("mre.trees")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/trees.py", line 3289, in load
    return TreeSequence.load(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/trees.py", line 4092, in load
    return TreeSequence(ts)
           ^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/trees.py", line 3985, in __init__
    name: metadata_module.parse_metadata_schema(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 735, in parse_metadata_schema
    return MetadataSchema(decoded)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 639, in __init__
    codec_instance = codec_cls(schema)
                     ^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 580, in __init__
    StructCodecSchemaValidator.check_schema(schema)
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/jsonschema/validators.py", line 301, in check_schema
    for error in validator.iter_errors(schema):
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/jsonschema/validators.py", line 368, in iter_errors
    for error in errors:
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 196, in binary_format_validator
    yield from jsonschema._validators.type(validator, types, instance, schema)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/jsonschema/__init__.py", line 105, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module jsonschema has no attribute _validators. Did you mean: 'validators'?
>>>
```

and for reference, the issue does not appear if msprime creates the tree sequences, e.g. via

```
$ msp  ancestry -o msprime.trees 1000
```

Note that the most basic SLiM tree sequence recipe also creates tskit output tskit cannot load: 

```
>>> import tskit
>>> tskit.load('recipe_17.1.trees')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/trees.py", line 3289, in load
    return TreeSequence.load(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/trees.py", line 4092, in load
    return TreeSequence(ts)
           ^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/trees.py", line 3985, in __init__
    name: metadata_module.parse_metadata_schema(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 735, in parse_metadata_schema
    return MetadataSchema(decoded)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 639, in __init__
    codec_instance = codec_cls(schema)
                     ^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 580, in __init__
    StructCodecSchemaValidator.check_schema(schema)
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/jsonschema/validators.py", line 301, in check_schema
    for error in validator.iter_errors(schema):
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/jsonschema/validators.py", line 368, in iter_errors
    for error in errors:
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/tskit/metadata.py", line 196, in binary_format_validator
    yield from jsonschema._validators.type(validator, types, instance, schema)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vsb/miniconda3/envs/mre/lib/python3.12/site-packages/jsonschema/__init__.py", line 105, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module jsonschema has no attribute _validators. Did you mean: 'validators'?
```

This is slim version 4.0.1 built from either source or the OS X executable. I am happy to post an issue on tskit too if the issue is on their side, but given msprime trees seem to load fine, this looked like a SLiM-specific issue to me.

Happy to provide any other information!

**Comment by bhaller** [comment]
Hi!  This is a known problem with recent versions of jsonschema and tskit.  See https://github.com/tskit-dev/pyslim/issues/329, https://github.com/tskit-dev/tskit/issues/2840.  A bug fix release of tskit is in the works; in the meantime, you can downgrade to an older version of jsonschema to fix the problem.  See details in those links.  Nothing to do with SLiM; closing.

**Comment by vsbuffalo** [comment]
Thanks Ben!
